"""Package materializer file manifests.

Keep source/target declarations here so package materialization logic can stay
focused on rendering, collision checks, and writing.
"""

from __future__ import annotations

DEFAULT_PACKAGE_CONFIG = "code-mower.example.yml"

PACKAGE_FILES = (
    ("tools/CODE_MOWER_APACHE_LICENSE.txt", "LICENSE", "package"),
    ("tools/CODE_MOWER_NOTICE.txt", "NOTICE", "package"),
    ("tools/code_mower_cli.py", "src/code_mower/cli.py", "core"),
    ("tools/code_mower_bootstrap.py", "src/code_mower/bootstrap.py", "core"),
    ("tools/code_mower_builder_experiment.py", "src/code_mower/builder_experiment.py", "core"),
    ("tools/code_mower_requirements.txt", "requirements/requirements.txt", "tooling"),
    ("tools/code_mower_calibration.py", "src/code_mower/code_mower_calibration.py", "core"),
    ("src/code_mower/checks.py", "src/code_mower/checks.py", "core"),
    ("src/code_mower/calibration/__init__.py", "src/code_mower/calibration/__init__.py", "core"),
    ("src/code_mower/calibration/auto_discovery.py", "src/code_mower/calibration/auto_discovery.py", "core"),
    ("src/code_mower/calibration/arms.py", "src/code_mower/calibration/arms.py", "core"),
    ("src/code_mower/calibration/commands.py", "src/code_mower/calibration/commands.py", "core"),
    ("src/code_mower/calibration/context_inputs.py", "src/code_mower/calibration/context_inputs.py", "core"),
    ("src/code_mower/calibration/corpus.py", "src/code_mower/calibration/corpus.py", "core"),
    ("src/code_mower/calibration/evidence.py", "src/code_mower/calibration/evidence.py", "core"),
    (
        "src/code_mower/calibration/evidence_report.py",
        "src/code_mower/calibration/evidence_report.py",
        "core",
    ),
    ("src/code_mower/calibration/identity.py", "src/code_mower/calibration/identity.py", "core"),
    ("src/code_mower/calibration/metrics.py", "src/code_mower/calibration/metrics.py", "core"),
    ("src/code_mower/calibration/overlap.py", "src/code_mower/calibration/overlap.py", "core"),
    ("src/code_mower/calibration/policy.py", "src/code_mower/calibration/policy.py", "core"),
    ("src/code_mower/calibration/planning.py", "src/code_mower/calibration/planning.py", "core"),
    ("src/code_mower/calibration/results.py", "src/code_mower/calibration/results.py", "core"),
    ("src/code_mower/calibration/run_results.py", "src/code_mower/calibration/run_results.py", "core"),
    ("src/code_mower/calibration/runner.py", "src/code_mower/calibration/runner.py", "core"),
    ("src/code_mower/calibration/run_status.py", "src/code_mower/calibration/run_status.py", "core"),
    ("src/code_mower/calibration/truth.py", "src/code_mower/calibration/truth.py", "core"),
    ("src/code_mower/calibration/value_report.py", "src/code_mower/calibration/value_report.py", "core"),
    ("tools/code_mower_cloud.py", "src/code_mower/cloud.py", "core"),
    ("src/code_mower/cloud_client/__init__.py", "src/code_mower/cloud_client/__init__.py", "core"),
    ("src/code_mower/cloud_client/bundle.py", "src/code_mower/cloud_client/bundle.py", "core"),
    ("src/code_mower/cloud_client/dogfood.py", "src/code_mower/cloud_client/dogfood.py", "core"),
    ("src/code_mower/cloud_client/doctor.py", "src/code_mower/cloud_client/doctor.py", "core"),
    ("src/code_mower/cloud_client/endpoints.py", "src/code_mower/cloud_client/endpoints.py", "core"),
    ("src/code_mower/cloud_client/errors.py", "src/code_mower/cloud_client/errors.py", "core"),
    ("src/code_mower/cloud_client/events.py", "src/code_mower/cloud_client/events.py", "core"),
    ("src/code_mower/cloud_client/export.py", "src/code_mower/cloud_client/export.py", "core"),
    (
        "src/code_mower/cloud_client/git_metadata.py",
        "src/code_mower/cloud_client/git_metadata.py",
        "core",
    ),
    ("src/code_mower/cloud_client/manifest.py", "src/code_mower/cloud_client/manifest.py", "core"),
    ("src/code_mower/cloud_client/operations.py", "src/code_mower/cloud_client/operations.py", "core"),
    ("src/code_mower/cloud_client/reports.py", "src/code_mower/cloud_client/reports.py", "core"),
    ("src/code_mower/cloud_client/setup.py", "src/code_mower/cloud_client/setup.py", "core"),
    ("src/code_mower/cloud_client/upload.py", "src/code_mower/cloud_client/upload.py", "core"),
    ("tools/code_mower_config.py", "src/code_mower/config.py", "core"),
    ("tools/code_mower_context_packs.py", "src/code_mower/code_mower_context_packs.py", "core"),
    ("tools/code_mower_doctor.py", "src/code_mower/doctor.py", "core"),
    ("src/code_mower/doctor_checks/__init__.py", "src/code_mower/doctor_checks/__init__.py", "core"),
    ("src/code_mower/doctor_checks/cloud.py", "src/code_mower/doctor_checks/cloud.py", "core"),
    ("src/code_mower/doctor_checks/common.py", "src/code_mower/doctor_checks/common.py", "core"),
    ("src/code_mower/doctor_checks/github_actions.py", "src/code_mower/doctor_checks/github_actions.py", "core"),
    (
        "src/code_mower/doctor_checks/github_actions_permissions.py",
        "src/code_mower/doctor_checks/github_actions_permissions.py",
        "core",
    ),
    (
        "src/code_mower/doctor_checks/github_actions_cost.py",
        "src/code_mower/doctor_checks/github_actions_cost.py",
        "core",
    ),
    (
        "src/code_mower/doctor_checks/github_actions_cost_summary.py",
        "src/code_mower/doctor_checks/github_actions_cost_summary.py",
        "core",
    ),
    (
        "src/code_mower/doctor_checks/github_actions_failures.py",
        "src/code_mower/doctor_checks/github_actions_failures.py",
        "core",
    ),
    (
        "src/code_mower/doctor_checks/github_actions_failure_annotations.py",
        "src/code_mower/doctor_checks/github_actions_failure_annotations.py",
        "core",
    ),
    (
        "src/code_mower/doctor_checks/github_actions_failure_models.py",
        "src/code_mower/doctor_checks/github_actions_failure_models.py",
        "core",
    ),
    (
        "src/code_mower/doctor_checks/github_actions_failure_scan.py",
        "src/code_mower/doctor_checks/github_actions_failure_scan.py",
        "core",
    ),
    (
        "src/code_mower/doctor_checks/github_actions_failure_selection.py",
        "src/code_mower/doctor_checks/github_actions_failure_selection.py",
        "core",
    ),
    ("src/code_mower/doctor_checks/github_api.py", "src/code_mower/doctor_checks/github_api.py", "core"),
    ("src/code_mower/doctor_checks/github_branch.py", "src/code_mower/doctor_checks/github_branch.py", "core"),
    ("src/code_mower/doctor_checks/github_config.py", "src/code_mower/doctor_checks/github_config.py", "core"),
    ("src/code_mower/doctor_checks/github.py", "src/code_mower/doctor_checks/github.py", "core"),
    (
        "src/code_mower/doctor_checks/github_provider.py",
        "src/code_mower/doctor_checks/github_provider.py",
        "core",
    ),
    ("src/code_mower/doctor_checks/github_repo.py", "src/code_mower/doctor_checks/github_repo.py", "core"),
    ("src/code_mower/doctor_checks/groups.py", "src/code_mower/doctor_checks/groups.py", "core"),
    ("src/code_mower/doctor_checks/models.py", "src/code_mower/doctor_checks/models.py", "core"),
    ("src/code_mower/doctor_checks/output.py", "src/code_mower/doctor_checks/output.py", "core"),
    ("src/code_mower/doctor_checks/presets.py", "src/code_mower/doctor_checks/presets.py", "core"),
    (
        "src/code_mower/doctor_checks/provider_api_model.py",
        "src/code_mower/doctor_checks/provider_api_model.py",
        "core",
    ),
    (
        "src/code_mower/doctor_checks/provider_api_model_openai.py",
        "src/code_mower/doctor_checks/provider_api_model_openai.py",
        "core",
    ),
    (
        "src/code_mower/doctor_checks/provider_api_model_profiles.py",
        "src/code_mower/doctor_checks/provider_api_model_profiles.py",
        "core",
    ),
    ("src/code_mower/doctor_checks/provider_env.py", "src/code_mower/doctor_checks/provider_env.py", "core"),
    (
        "src/code_mower/doctor_checks/provider_env_required.py",
        "src/code_mower/doctor_checks/provider_env_required.py",
        "core",
    ),
    (
        "src/code_mower/doctor_checks/provider_env_tokens.py",
        "src/code_mower/doctor_checks/provider_env_tokens.py",
        "core",
    ),
    (
        "src/code_mower/doctor_checks/provider_local_cli.py",
        "src/code_mower/doctor_checks/provider_local_cli.py",
        "core",
    ),
    (
        "src/code_mower/doctor_checks/provider_local_cli_commands.py",
        "src/code_mower/doctor_checks/provider_local_cli_commands.py",
        "core",
    ),
    (
        "src/code_mower/doctor_checks/provider_local_cli_probe_config.py",
        "src/code_mower/doctor_checks/provider_local_cli_probe_config.py",
        "core",
    ),
    ("src/code_mower/doctor_checks/provider_probe.py", "src/code_mower/doctor_checks/provider_probe.py", "core"),
    (
        "src/code_mower/doctor_checks/provider_probe_auth.py",
        "src/code_mower/doctor_checks/provider_probe_auth.py",
        "core",
    ),
    (
        "src/code_mower/doctor_checks/provider_probe_evaluation.py",
        "src/code_mower/doctor_checks/provider_probe_evaluation.py",
        "core",
    ),
    (
        "src/code_mower/doctor_checks/provider_probe_json.py",
        "src/code_mower/doctor_checks/provider_probe_json.py",
        "core",
    ),
    (
        "src/code_mower/doctor_checks/provider_probe_remediation.py",
        "src/code_mower/doctor_checks/provider_probe_remediation.py",
        "core",
    ),
    ("src/code_mower/doctor_checks/privacy.py", "src/code_mower/doctor_checks/privacy.py", "core"),
    ("src/code_mower/doctor_checks/providers.py", "src/code_mower/doctor_checks/providers.py", "core"),
    ("src/code_mower/doctor_checks/registry.py", "src/code_mower/doctor_checks/registry.py", "core"),
    ("src/code_mower/doctor_checks/runner.py", "src/code_mower/doctor_checks/runner.py", "core"),
    ("src/code_mower/doctor_checks/runtime.py", "src/code_mower/doctor_checks/runtime.py", "core"),
    (
        "src/code_mower/doctor_checks/runtime_github_auth.py",
        "src/code_mower/doctor_checks/runtime_github_auth.py",
        "core",
    ),
    ("tools/code_mower_init.py", "src/code_mower/init.py", "core"),
    ("tools/code_mower_merge.py", "src/code_mower/code_mower_merge.py", "core"),
    ("src/code_mower/migration.py", "src/code_mower/migration.py", "core"),
    ("src/code_mower/migration_install.py", "src/code_mower/migration_install.py", "core"),
    ("src/code_mower/migration_mirror.py", "src/code_mower/migration_mirror.py", "core"),
    ("src/code_mower/migration_readiness.py", "src/code_mower/migration_readiness.py", "core"),
    ("src/code_mower/migration_rehearsal.py", "src/code_mower/migration_rehearsal.py", "core"),
    ("tools/code_mower_next_steps.py", "src/code_mower/next_steps.py", "core"),
    ("tools/code_mower_package.py", "src/code_mower/package.py", "core"),
    ("tools/code_mower_package_content.py", "src/code_mower/package_content.py", "core"),
    ("tools/code_mower_package_manifest.py", "src/code_mower/package_manifest.py", "core"),
    ("src/code_mower/package_paths.py", "src/code_mower/package_paths.py", "core"),
    ("tools/code_mower_package_rendering.py", "src/code_mower/package_rendering.py", "core"),
    ("tools/code_mower_package_static.py", "src/code_mower/package_static.py", "core"),
    ("tools/code_mower_versioning.py", "src/code_mower/versioning.py", "core"),
    ("tools/code_mower_prompts.py", "src/code_mower/prompts.py", "core"),
    ("src/code_mower/release_readiness.py", "src/code_mower/release_readiness.py", "core"),
    ("tools/code_mower_secrets.py", "src/code_mower/secrets.py", "core"),
    ("tools/code_mower_telemetry.py", "src/code_mower/code_mower_telemetry.py", "core"),
    ("tools/reviewer_metrics.py", "src/code_mower/reviewer_metrics.py", "core"),
    ("tools/provider_registry.py", "src/code_mower/provider_registry.py", "core"),
    ("tools/blind_review_coordinator.py", "src/code_mower/blind_review_coordinator.py", "core"),
    ("tools/blind_review_artifacts.py", "src/code_mower/blind_review_artifacts.py", "core"),
    ("tools/audit_handoff_log.py", "src/code_mower/audit_handoff_log.py", "core"),
    ("tools/audit_labeler_lib.py", "src/code_mower/audit_labeler_lib.py", "core"),
    ("tools/audit_progress.py", "src/code_mower/audit_progress.py", "core"),
    (
        "src/code_mower/provider_runners/__init__.py",
        "src/code_mower/provider_runners/__init__.py",
        "reviewer",
    ),
    (
        "src/code_mower/provider_runners/comments.py",
        "src/code_mower/provider_runners/comments.py",
        "reviewer",
    ),
    (
        "src/code_mower/provider_runners/git.py",
        "src/code_mower/provider_runners/git.py",
        "reviewer",
    ),
    (
        "src/code_mower/provider_runners/github_auth.py",
        "src/code_mower/provider_runners/github_auth.py",
        "reviewer",
    ),
    (
        "src/code_mower/provider_runners/github_pr.py",
        "src/code_mower/provider_runners/github_pr.py",
        "reviewer",
    ),
    (
        "src/code_mower/provider_runners/process.py",
        "src/code_mower/provider_runners/process.py",
        "reviewer",
    ),
    (
        "src/code_mower/provider_runners/repo_paths.py",
        "src/code_mower/provider_runners/repo_paths.py",
        "reviewer",
    ),
    (
        "src/code_mower/provider_runners/text_schema.py",
        "src/code_mower/provider_runners/text_schema.py",
        "reviewer",
    ),
    (
        "src/code_mower/provider_runners/verdict_artifacts.py",
        "src/code_mower/provider_runners/verdict_artifacts.py",
        "reviewer",
    ),
    (
        "src/code_mower/provider_runners/workspace.py",
        "src/code_mower/provider_runners/workspace.py",
        "reviewer",
    ),
    ("tools/codex_audit_pr.py", "src/code_mower/codex_audit_pr.py", "reviewer"),
    (
        "tools/codex_audit_env_preflight.py",
        "src/code_mower/codex_audit_env_preflight.py",
        "reviewer",
    ),
    (
        "tools/codex_audit_schema_smoke.py",
        "src/code_mower/codex_audit_schema_smoke.py",
        "reviewer",
    ),
    (
        "tools/codex_audit_verdict.schema.json",
        "src/code_mower/codex_audit_verdict.schema.json",
        "reviewer",
    ),
    ("tools/claude_audit_pr.py", "src/code_mower/claude_audit_pr.py", "reviewer"),
    ("src/code_mower/claude_cli_bounce.py", "src/code_mower/claude_cli_bounce.py", "reviewer"),
    (
        "src/code_mower/claude_cli_environment.py",
        "src/code_mower/claude_cli_environment.py",
        "reviewer",
    ),
    ("src/code_mower/clear_stale.py", "src/code_mower/clear_stale.py", "labeler"),
    ("tools/trailer_comment_labeler.py", "src/code_mower/trailer_comment_labeler.py", "labeler"),
    ("tools/saas_reviewer_labeler.py", "src/code_mower/saas_reviewer_labeler.py", "labeler"),
    ("tools/local_llm_audit_pr.py", "src/code_mower/local_llm_audit_pr.py", "reviewer"),
    ("tools/local_llm_bakeoff.py", "src/code_mower/local_llm_bakeoff.py", "reviewer"),
    ("tools/local_llm_calibration.py", "src/code_mower/local_llm_calibration.py", "reviewer"),
    ("tools/local_llm_profiles.py", "src/code_mower/local_llm_profiles.py", "reviewer"),
    ("tools/gemini_cli_audit_pr.py", "src/code_mower/gemini_cli_audit_pr.py", "reviewer"),
    ("tools/antigravity_cli_audit_pr.py", "src/code_mower/antigravity_cli_audit_pr.py", "reviewer"),
    ("tools/hermes_cli_audit_pr.py", "src/code_mower/hermes_cli_audit_pr.py", "reviewer"),
    ("tools/coderabbit_cli_audit_pr.py", "src/code_mower/coderabbit_cli_audit_pr.py", "reviewer"),
    ("tools/lane_configs/__init__.py", "src/code_mower/lane_configs/__init__.py", "lane-config"),
    ("tools/lane_configs/claude.py", "src/code_mower/lane_configs/claude.py", "lane-config"),
    ("tools/lane_configs/codex.py", "src/code_mower/lane_configs/codex.py", "lane-config"),
    ("tools/lane_configs/devin.py", "src/code_mower/lane_configs/devin.py", "lane-config"),
    ("tools/lane_configs/local_llm.py", "src/code_mower/lane_configs/local_llm.py", "lane-config"),
    ("tools/lane_configs/aider.py", "src/code_mower/lane_configs/aider.py", "lane-config"),
    ("tools/lane_configs/gemini_cli.py", "src/code_mower/lane_configs/gemini_cli.py", "lane-config"),
    ("tools/lane_configs/antigravity_cli.py", "src/code_mower/lane_configs/antigravity_cli.py", "lane-config"),
    ("tools/lane_configs/hermes_cli.py", "src/code_mower/lane_configs/hermes_cli.py", "lane-config"),
    ("tools/lane_prompts/base-audit.md", "src/code_mower/templates/lane_prompts/base-audit.md", "prompt"),
    ("tools/lane_prompts/calibration-policy.md", "src/code_mower/templates/lane_prompts/calibration-policy.md", "prompt"),
    (
        "tools/lane_prompts/context-driven-quality.md",
        "src/code_mower/templates/lane_prompts/context-driven-quality.md",
        "prompt",
    ),
    ("tools/lane_prompts/docs-design.md", "src/code_mower/templates/lane_prompts/docs-design.md", "prompt"),
    (
        "tools/lane_prompts/generic-programming.md",
        "src/code_mower/templates/lane_prompts/generic-programming.md",
        "prompt",
    ),
    ("tools/lane_prompts/operability.md", "src/code_mower/templates/lane_prompts/operability.md", "prompt"),
    ("tools/lane_prompts/package-runtime.md", "src/code_mower/templates/lane_prompts/package-runtime.md", "prompt"),
    (
        "tools/lane_prompts/security-threat-model.md",
        "src/code_mower/templates/lane_prompts/security-threat-model.md",
        "prompt",
    ),
    ("code-mower.example.yml", "src/code_mower/templates/code-mower.example.yml", "config"),
    ("tools/calibration_corpus.example.json", "templates/calibration-corpus.json", "config"),
    ("tools/calibration_corpus.example.json", "templates/calibration-corpus.example.json", "config"),
    ("tools/builder_experiment.example.json", "templates/builder-experiment.example.json", "config"),
    ("tools/context_packs.example.json", "templates/context-packs.example.json", "config"),
    ("tools/reviewer_spend.example.json", "templates/reviewer-spend.example.json", "config"),
    ("tools/reviewer_value_report.example.md", "templates/reviewer-value-report.example.md", "config"),
    (".cursor/BUGBOT.md", "templates/cursor/BUGBOT.md", "config"),
    (
        "tools/calibration_corpus.example.json",
        "src/code_mower/templates/calibration-corpus.json",
        "config",
    ),
    (
        "tools/calibration_corpus.example.json",
        "src/code_mower/templates/calibration-corpus.example.json",
        "config",
    ),
    (
        "tools/builder_experiment.example.json",
        "src/code_mower/templates/builder-experiment.example.json",
        "config",
    ),
    ("tools/context_packs.example.json", "src/code_mower/templates/context-packs.example.json", "config"),
    ("tools/reviewer_spend.example.json", "src/code_mower/templates/reviewer-spend.example.json", "config"),
    (
        "tools/reviewer_value_report.example.md",
        "src/code_mower/templates/reviewer-value-report.example.md",
        "config",
    ),
    (
        "src/code_mower/templates/product-support/code_mower",
        "src/code_mower/templates/product-support/code_mower",
        "template",
    ),
    (
        "src/code_mower/templates/product-support/code_mower_standalone_pin.env",
        "src/code_mower/templates/product-support/code_mower_standalone_pin.env",
        "template",
    ),
    (
        "src/code_mower/templates/product-support/code_mower_standalone_shadow.sh",
        "src/code_mower/templates/product-support/code_mower_standalone_shadow.sh",
        "template",
    ),
    (
        "src/code_mower/templates/product-support/run_claude_audit_pr.sh",
        "src/code_mower/templates/product-support/run_claude_audit_pr.sh",
        "template",
    ),
    (
        "src/code_mower/templates/product-support/run_codex_audit_pr.sh",
        "src/code_mower/templates/product-support/run_codex_audit_pr.sh",
        "template",
    ),
    (
        "src/code_mower/templates/product-support/safe_gh_comment.py",
        "src/code_mower/templates/product-support/safe_gh_comment.py",
        "template",
    ),
    ("tools/ACP_BRIDGE_SPIKE.md", "docs/acp-bridge-spike.md", "doc"),
    ("tools/CODE_MOWER_CALIBRATION_PILOT.md", "docs/calibration-pilot.md", "doc"),
    ("tools/CODE_MOWER_CALIBRATION_NOTES.md", "docs/calibration-notes.md", "doc"),
    ("tools/CODE_MOWER_LENS_CALIBRATION_REPORT.md", "docs/lens-calibration-report.md", "doc"),
    ("tools/CODE_MOWER_REVIEWER_VALUE_REPORT.md", "docs/reviewer-value-report.md", "doc"),
    ("tools/CODE_MOWER_LANE_PROMOTION_POLICY.md", "docs/lane-promotion-policy.md", "doc"),
    ("tools/CODE_MOWER_PACKAGE_CUSTOMIZATION.md", "docs/package-customization.md", "doc"),
    ("tools/CODE_MOWER_AUTHORING_INTELLIGENCE.md", "docs/authoring-intelligence.md", "doc"),
    ("tools/CODE_MOWER_BUILDER_EXPERIMENTS.md", "docs/builder-experiments.md", "doc"),
    ("tools/CODE_MOWER_CLOUD_BENCHMARKING.md", "docs/cloud-benchmarking.md", "doc"),
    ("tools/CODE_MOWER_REPO_STRATEGY.md", "docs/repo-strategy.md", "doc"),
    ("tools/CODE_MOWER_COMMERCIAL_BOUNDARY.md", "docs/commercial-boundary.md", "doc"),
    ("tools/CODE_MOWER_PUBLIC_RELEASE_CHECKLIST.md", "docs/public-release-checklist.md", "doc"),
    ("tools/CODE_MOWER_GITHUB_SETUP.md", "docs/github-setup.md", "doc"),
    ("docs/troubleshooting.md", "docs/troubleshooting.md", "doc"),
    (
        "tools/CODE_MOWER_MIRROR_REMOVAL_RUNBOOK.md",
        "docs/mirror-removal-runbook.md",
        "doc",
    ),
    ("tools/CODE_MOWER_PROVIDER_MATRIX.md", "docs/provider-matrix.md", "doc"),
    ("tools/CODE_MOWER_OSS_V1_CHECKLIST.md", "docs/oss-v1-checklist.md", "doc"),
    ("tools/adapters/__init__.py", "src/code_mower/adapters/__init__.py", "adapter"),
    ("tools/adapters/_base.py", "src/code_mower/adapters/_base.py", "adapter"),
    ("tools/adapters/cursor_bugbot.py", "src/code_mower/adapters/cursor_bugbot.py", "adapter"),
    ("tools/adapters/gitar.py", "src/code_mower/adapters/gitar.py", "adapter"),
    ("tools/adapters/greptile.py", "src/code_mower/adapters/greptile.py", "adapter"),
    ("tools/adapters/qodo.py", "src/code_mower/adapters/qodo.py", "adapter"),
)

DEFERRED_PACKAGE_FILES = (
    (
        "tools/local_llm_audit_bridge.py",
        "src/code_mower/local_llm_audit_bridge.py",
        "daemon defaults and scheduling policy remain repo-local",
    ),
)

TEMPLATE_FILES = (
    ("package", "LICENSE"),
    ("package", "NOTICE"),
    ("package", "pyproject.toml"),
    ("package", "README.md"),
    ("package", "MANIFEST.in"),
    ("package", ".gitignore"),
    ("workflow", "templates/workflows/trailer-comment-labeler.yml.j2"),
    ("workflow", "templates/workflows/saas-reviewer-labeler.yml.j2"),
    ("workflow", "templates/workflows/local-cli-audit.yml.j2"),
    ("workflow", "templates/workflows/blind-review-artifacts-dry-run.yml.j2"),
    ("workflow", "templates/workflows/hosted-bridge.yml.j2"),
    ("workflow", "templates/workflows/audit-label-cleanup.yml.j2"),
    ("workflow", "templates/workflows/review-clear-stale.yml.j2"),
    ("workflow", "src/code_mower/templates/workflows/review-clear-stale.yml.j2"),
    ("workflow", "templates/workflows/private-standalone-shadow.yml.j2"),
    ("workflow", "src/code_mower/templates/workflows/private-standalone-shadow.yml.j2"),
    ("config", "templates/code-mower.yml.j2"),
    ("provider-config", "templates/providers.yml"),
    ("provider-catalog", "src/code_mower/templates/providers.yml"),
)
