#!/usr/bin/env python3
"""Run actionlint against every workflow generated by easy-mode init."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


CONFIG = """\
self-hosted-runner:
  labels:
    - code-mower-audit
"""
IGNORES = ("SC2016", "SC2034")
SCRATCH_GIT_USER_NAME_FALLBACK = "Code Mower Scratch"
SCRATCH_GIT_USER_EMAIL_FALLBACK = "code-mower-scratch@example.com"


def _scratch_git_identity() -> tuple[str, str]:
    source_root = Path(__file__).resolve().parents[1] / "src"
    if source_root.is_dir() and str(source_root) not in sys.path:
        sys.path.insert(0, str(source_root))
    try:
        from code_mower.git_identity import (
            SCRATCH_GIT_USER_EMAIL,
            SCRATCH_GIT_USER_NAME,
        )
    except ModuleNotFoundError:
        return SCRATCH_GIT_USER_NAME_FALLBACK, SCRATCH_GIT_USER_EMAIL_FALLBACK
    return SCRATCH_GIT_USER_NAME, SCRATCH_GIT_USER_EMAIL


def _resolve_executable(value: str) -> Path:
    resolved = shutil.which(value)
    if resolved:
        return Path(resolved).resolve()
    return Path(value).expanduser().resolve()


def _default_code_mower_bin() -> str:
    resolved = shutil.which("code-mower")
    if resolved:
        return resolved
    for parent in (Path(sys.executable).parent, Path(sys.executable).resolve().parent):
        candidate = parent / "code-mower"
        if candidate.is_file():
            return str(candidate)
    return "code-mower"


def _run(command: list[str], *, cwd: Path, env: dict[str, str]) -> None:
    completed = subprocess.run(
        command,
        cwd=cwd,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    if completed.returncode == 0:
        return
    payload = {
        "command": command,
        "cwd": str(cwd),
        "returncode": completed.returncode,
        "stdout": completed.stdout[-4000:],
        "stderr": completed.stderr[-4000:],
    }
    raise RuntimeError(json.dumps(payload, indent=2, sort_keys=True))


def _prepare_repo(repo: Path, env: dict[str, str]) -> None:
    repo.mkdir(parents=True)
    (repo / "README.md").write_text("# Code Mower actionlint toy repo\n", encoding="utf-8")
    git = shutil.which("git")
    if not git:
        return
    scratch_name, scratch_email = _scratch_git_identity()
    _run([git, "init", "-q"], cwd=repo, env=env)
    _run([git, "config", "user.name", scratch_name], cwd=repo, env=env)
    _run([git, "config", "user.email", scratch_email], cwd=repo, env=env)
    _run([git, "config", "commit.gpgSign", "false"], cwd=repo, env=env)
    _run([git, "add", "README.md"], cwd=repo, env=env)
    _run(
        [git, "-c", "commit.gpgSign=false", "commit", "-q", "-m", "Initial toy repo"],
        cwd=repo,
        env=env,
    )


def run_actionlint_generated(
    *,
    code_mower_bin: Path,
    actionlint_bin: Path,
    work_dir: Path,
) -> dict[str, object]:
    if not code_mower_bin.is_file():
        raise RuntimeError(f"code-mower executable not found: {code_mower_bin}")
    if not actionlint_bin.is_file():
        raise RuntimeError(f"actionlint executable not found: {actionlint_bin}")

    repo = work_dir / "toy-repo"
    if repo.exists():
        shutil.rmtree(repo)
    env = os.environ.copy()
    env["PATH"] = (
        f"{code_mower_bin.parent}{os.pathsep}"
        f"{actionlint_bin.parent}{os.pathsep}"
        f"{env.get('PATH', '')}"
    )
    _prepare_repo(repo, env)

    _run(
        [
            str(code_mower_bin),
            "init",
            "--easy",
            "--apply",
            "--output-dir",
            ".code-mower.generated",
            "--json",
        ],
        cwd=repo,
        env=env,
    )

    workflows = tuple(sorted((repo / ".code-mower.generated/.github/workflows").glob("*.yml")))
    if not workflows:
        raise RuntimeError("easy-mode init did not generate workflow files")

    config_path = work_dir / "actionlint-self-hosted.yml"
    config_path.write_text(CONFIG, encoding="utf-8")
    command = [str(actionlint_bin), "-config-file", str(config_path)]
    for code in IGNORES:
        command.extend(("-ignore", code))
    command.extend(str(path) for path in workflows)
    _run(command, cwd=repo, env=env)

    return {
        "work_dir": str(work_dir),
        "workflow_count": len(workflows),
        "workflows": [str(path.relative_to(repo)) for path in workflows],
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--code-mower-bin", default=_default_code_mower_bin())
    parser.add_argument("--actionlint-bin", default="actionlint")
    parser.add_argument("--work-dir", type=Path)
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args(argv)

    try:
        if args.work_dir:
            result = run_actionlint_generated(
                code_mower_bin=_resolve_executable(args.code_mower_bin),
                actionlint_bin=_resolve_executable(args.actionlint_bin),
                work_dir=args.work_dir.resolve(),
            )
        else:
            with tempfile.TemporaryDirectory(prefix="code-mower-actionlint-") as raw:
                result = run_actionlint_generated(
                    code_mower_bin=_resolve_executable(args.code_mower_bin),
                    actionlint_bin=_resolve_executable(args.actionlint_bin),
                    work_dir=Path(raw),
                )
    except RuntimeError as exc:
        print(f"generated workflow actionlint failed: {exc}", file=sys.stderr)
        return 1

    if args.json:
        print(json.dumps(result, indent=2, sort_keys=True))
    else:
        print(f"actionlint passed for {result['workflow_count']} generated workflows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
